/**
 * Mock/seed data for Horizon DevSecOps Portal prototype phase
 * @module mockData
 */

import { v4 as uuidv4 } from 'uuid';
import {
  DOMAINS,
  PORTFOLIOS,
  APPLICATIONS,
  CRITICALITY_TIERS,
  ENVIRONMENTS,
  ROLES,
  TOOLS,
  TOOLCHAIN_CATEGORIES,
  PIPELINE_STAGES,
  PIPELINE_STATUSES,
  KPI_METRICS,
  COMPLIANCE_ARTIFACT_TYPES,
  COMPLIANCE_STATUSES,
  SEVERITY_LEVELS,
} from './constants.js';

// ---------------------------------------------------------------------------
// Helper Utilities
// ---------------------------------------------------------------------------

/**
 * Generate a deterministic-looking but unique ID with a prefix.
 * @param {string} prefix
 * @param {number} index
 * @returns {string}
 */
const makeId = (prefix, index) => `${prefix}-${String(index).padStart(4, '0')}`;

/**
 * Generate a random date within a range.
 * @param {Date} start
 * @param {Date} end
 * @returns {string} ISO date string
 */
const randomDate = (start, end) => {
  const d = new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  return d.toISOString();
};

/**
 * Pick a random element from an array.
 * @param {Array} arr
 * @returns {*}
 */
const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];

// ---------------------------------------------------------------------------
// Mock Users
// ---------------------------------------------------------------------------
export const MOCK_USERS = Object.freeze([
  {
    id: makeId('USR', 1),
    username: 'admin.horizon',
    email: 'admin@horizon.example.com',
    firstName: 'Alex',
    lastName: 'Morgan',
    role: ROLES.ADMIN,
    department: 'Platform Engineering',
    avatar: null,
    lastLogin: '2024-11-10T08:30:00Z',
    active: true,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('USR', 2),
    username: 'sarah.chen',
    email: 'sarah.chen@horizon.example.com',
    firstName: 'Sarah',
    lastName: 'Chen',
    role: ROLES.ENGINEER,
    department: 'Digital Experience',
    avatar: null,
    lastLogin: '2024-11-09T14:22:00Z',
    active: true,
    createdAt: '2023-03-20T09:00:00Z',
  },
  {
    id: makeId('USR', 3),
    username: 'james.wilson',
    email: 'james.wilson@horizon.example.com',
    firstName: 'James',
    lastName: 'Wilson',
    role: ROLES.OWNER,
    department: 'Health and Network',
    avatar: null,
    lastLogin: '2024-11-10T07:15:00Z',
    active: true,
    createdAt: '2023-02-10T11:00:00Z',
  },
  {
    id: makeId('USR', 4),
    username: 'priya.patel',
    email: 'priya.patel@horizon.example.com',
    firstName: 'Priya',
    lastName: 'Patel',
    role: ROLES.AUDITOR,
    department: 'Security and Compliance',
    avatar: null,
    lastLogin: '2024-11-08T16:45:00Z',
    active: true,
    createdAt: '2023-04-05T08:30:00Z',
  },
  {
    id: makeId('USR', 5),
    username: 'michael.ross',
    email: 'michael.ross@horizon.example.com',
    firstName: 'Michael',
    lastName: 'Ross',
    role: ROLES.EXECUTIVE,
    department: 'Corporate Functions',
    avatar: null,
    lastLogin: '2024-11-10T09:00:00Z',
    active: true,
    createdAt: '2023-01-10T10:00:00Z',
  },
  {
    id: makeId('USR', 6),
    username: 'lisa.nguyen',
    email: 'lisa.nguyen@horizon.example.com',
    firstName: 'Lisa',
    lastName: 'Nguyen',
    role: ROLES.ENGINEER,
    department: 'Data and Analytics',
    avatar: null,
    lastLogin: '2024-11-09T11:30:00Z',
    active: true,
    createdAt: '2023-05-12T14:00:00Z',
  },
  {
    id: makeId('USR', 7),
    username: 'david.kumar',
    email: 'david.kumar@horizon.example.com',
    firstName: 'David',
    lastName: 'Kumar',
    role: ROLES.ENGINEER,
    department: 'Infrastructure Services',
    avatar: null,
    lastLogin: '2024-11-10T06:50:00Z',
    active: true,
    createdAt: '2023-06-01T09:00:00Z',
  },
  {
    id: makeId('USR', 8),
    username: 'emma.johnson',
    email: 'emma.johnson@horizon.example.com',
    firstName: 'Emma',
    lastName: 'Johnson',
    role: ROLES.OWNER,
    department: 'Enterprise Platforms',
    avatar: null,
    lastLogin: '2024-11-09T17:20:00Z',
    active: true,
    createdAt: '2023-03-15T10:30:00Z',
  },
]);

// ---------------------------------------------------------------------------
// Mock Domains
// ---------------------------------------------------------------------------
export const MOCK_DOMAINS = Object.freeze([
  {
    id: makeId('DOM', 1),
    name: DOMAINS.CORPORATE_FUNCTIONS,
    description: 'Finance, HR, Legal, and Marketing business functions.',
    owner: MOCK_USERS[4].id,
    portfolioCount: 4,
    applicationCount: 5,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 2),
    name: DOMAINS.HEALTH_AND_NETWORK,
    description: 'Network operations and health monitoring systems.',
    owner: MOCK_USERS[2].id,
    portfolioCount: 2,
    applicationCount: 3,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 3),
    name: DOMAINS.DIGITAL_EXPERIENCE,
    description: 'Customer-facing portals and mobile applications.',
    owner: MOCK_USERS[1].id,
    portfolioCount: 2,
    applicationCount: 4,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 4),
    name: DOMAINS.DATA_AND_ANALYTICS,
    description: 'Data platform, analytics engine, and BI reporting.',
    owner: MOCK_USERS[5].id,
    portfolioCount: 2,
    applicationCount: 3,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 5),
    name: DOMAINS.SECURITY_AND_COMPLIANCE,
    description: 'Identity, access management, and threat detection.',
    owner: MOCK_USERS[3].id,
    portfolioCount: 2,
    applicationCount: 2,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 6),
    name: DOMAINS.INFRASTRUCTURE_SERVICES,
    description: 'Cloud and on-premises infrastructure management.',
    owner: MOCK_USERS[6].id,
    portfolioCount: 2,
    applicationCount: 2,
    createdAt: '2023-01-15T10:00:00Z',
  },
  {
    id: makeId('DOM', 7),
    name: DOMAINS.ENTERPRISE_PLATFORMS,
    description: 'ERP, CRM, and enterprise integration platforms.',
    owner: MOCK_USERS[7].id,
    portfolioCount: 2,
    applicationCount: 2,
    createdAt: '2023-01-15T10:00:00Z',
  },
]);

// ---------------------------------------------------------------------------
// Mock Portfolios
// ---------------------------------------------------------------------------
export const MOCK_PORTFOLIOS = Object.freeze([
  {
    id: makeId('PRT', 1),
    name: PORTFOLIOS.FINANCE,
    domainId: MOCK_DOMAINS[0].id,
    domainName: DOMAINS.CORPORATE_FUNCTIONS,
    owner: MOCK_USERS[4].id,
    applicationCount: 2,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 2),
    name: PORTFOLIOS.HR,
    domainId: MOCK_DOMAINS[0].id,
    domainName: DOMAINS.CORPORATE_FUNCTIONS,
    owner: MOCK_USERS[4].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 3),
    name: PORTFOLIOS.NETWORK_OPS,
    domainId: MOCK_DOMAINS[1].id,
    domainName: DOMAINS.HEALTH_AND_NETWORK,
    owner: MOCK_USERS[2].id,
    applicationCount: 2,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 4),
    name: PORTFOLIOS.HEALTH_MONITORING,
    domainId: MOCK_DOMAINS[1].id,
    domainName: DOMAINS.HEALTH_AND_NETWORK,
    owner: MOCK_USERS[2].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 5),
    name: PORTFOLIOS.CUSTOMER_PORTAL,
    domainId: MOCK_DOMAINS[2].id,
    domainName: DOMAINS.DIGITAL_EXPERIENCE,
    owner: MOCK_USERS[1].id,
    applicationCount: 2,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 6),
    name: PORTFOLIOS.MOBILE_APPS,
    domainId: MOCK_DOMAINS[2].id,
    domainName: DOMAINS.DIGITAL_EXPERIENCE,
    owner: MOCK_USERS[1].id,
    applicationCount: 2,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 7),
    name: PORTFOLIOS.DATA_PLATFORM,
    domainId: MOCK_DOMAINS[3].id,
    domainName: DOMAINS.DATA_AND_ANALYTICS,
    owner: MOCK_USERS[5].id,
    applicationCount: 2,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 8),
    name: PORTFOLIOS.ANALYTICS_ENGINE,
    domainId: MOCK_DOMAINS[3].id,
    domainName: DOMAINS.DATA_AND_ANALYTICS,
    owner: MOCK_USERS[5].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 9),
    name: PORTFOLIOS.IDENTITY_ACCESS,
    domainId: MOCK_DOMAINS[4].id,
    domainName: DOMAINS.SECURITY_AND_COMPLIANCE,
    owner: MOCK_USERS[3].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 10),
    name: PORTFOLIOS.THREAT_MANAGEMENT,
    domainId: MOCK_DOMAINS[4].id,
    domainName: DOMAINS.SECURITY_AND_COMPLIANCE,
    owner: MOCK_USERS[3].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 11),
    name: PORTFOLIOS.CLOUD_INFRA,
    domainId: MOCK_DOMAINS[5].id,
    domainName: DOMAINS.INFRASTRUCTURE_SERVICES,
    owner: MOCK_USERS[6].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 12),
    name: PORTFOLIOS.ON_PREM_INFRA,
    domainId: MOCK_DOMAINS[5].id,
    domainName: DOMAINS.INFRASTRUCTURE_SERVICES,
    owner: MOCK_USERS[6].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 13),
    name: PORTFOLIOS.ERP,
    domainId: MOCK_DOMAINS[6].id,
    domainName: DOMAINS.ENTERPRISE_PLATFORMS,
    owner: MOCK_USERS[7].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
  {
    id: makeId('PRT', 14),
    name: PORTFOLIOS.CRM,
    domainId: MOCK_DOMAINS[6].id,
    domainName: DOMAINS.ENTERPRISE_PLATFORMS,
    owner: MOCK_USERS[7].id,
    applicationCount: 1,
    createdAt: '2023-01-20T10:00:00Z',
  },
]);

// ---------------------------------------------------------------------------
// Mock Applications (Onboarded)
// ---------------------------------------------------------------------------
export const MOCK_APPLICATIONS = Object.freeze([
  {
    id: makeId('APP', 1),
    name: 'Member Portal',
    shortCode: 'MBRP',
    description: 'Customer-facing member portal for account management, claims, and benefits.',
    domainId: MOCK_DOMAINS[2].id,
    domainName: DOMAINS.DIGITAL_EXPERIENCE,
    portfolioId: MOCK_PORTFOLIOS[4].id,
    portfolioName: PORTFOLIOS.CUSTOMER_PORTAL,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[1].id,
    ownerName: 'Sarah Chen',
    techStack: ['React', 'Node.js', 'PostgreSQL', 'Redis'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-06-15T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/member-portal',
    tags: ['customer-facing', 'high-traffic', 'pci-compliant'],
  },
  {
    id: makeId('APP', 2),
    name: 'Care Radius',
    shortCode: 'CRAD',
    description: 'Provider network management and care coordination platform.',
    domainId: MOCK_DOMAINS[1].id,
    domainName: DOMAINS.HEALTH_AND_NETWORK,
    portfolioId: MOCK_PORTFOLIOS[2].id,
    portfolioName: PORTFOLIOS.NETWORK_OPS,
    criticalityTier: CRITICALITY_TIERS.MISSION_CRITICAL,
    owner: MOCK_USERS[2].id,
    ownerName: 'James Wilson',
    techStack: ['Java', 'Spring Boot', 'Oracle', 'Kafka'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-05-20T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/care-radius',
    tags: ['hipaa', 'mission-critical', 'provider-network'],
  },
  {
    id: makeId('APP', 3),
    name: 'API Gateway',
    shortCode: 'APIG',
    description: 'Centralized API gateway for routing, rate limiting, and authentication across all services.',
    domainId: MOCK_DOMAINS[5].id,
    domainName: DOMAINS.INFRASTRUCTURE_SERVICES,
    portfolioId: MOCK_PORTFOLIOS[10].id,
    portfolioName: PORTFOLIOS.CLOUD_INFRA,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[6].id,
    ownerName: 'David Kumar',
    techStack: ['Go', 'Kubernetes', 'Redis', 'Envoy'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-04-10T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/api-gateway',
    tags: ['infrastructure', 'high-availability', 'zero-trust'],
  },
  {
    id: makeId('APP', 4),
    name: 'Network Monitoring System',
    shortCode: 'NMS',
    description: 'Real-time network health monitoring, alerting, and diagnostics platform.',
    domainId: MOCK_DOMAINS[1].id,
    domainName: DOMAINS.HEALTH_AND_NETWORK,
    portfolioId: MOCK_PORTFOLIOS[3].id,
    portfolioName: PORTFOLIOS.HEALTH_MONITORING,
    criticalityTier: CRITICALITY_TIERS.MISSION_CRITICAL,
    owner: MOCK_USERS[2].id,
    ownerName: 'James Wilson',
    techStack: ['Python', 'FastAPI', 'InfluxDB', 'Grafana'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-07-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/nms',
    tags: ['monitoring', 'real-time', 'alerting'],
  },
  {
    id: makeId('APP', 5),
    name: APPLICATIONS.GENERAL_LEDGER,
    shortCode: 'GLED',
    description: 'Enterprise general ledger and financial accounting system.',
    domainId: MOCK_DOMAINS[0].id,
    domainName: DOMAINS.CORPORATE_FUNCTIONS,
    portfolioId: MOCK_PORTFOLIOS[0].id,
    portfolioName: PORTFOLIOS.FINANCE,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[4].id,
    ownerName: 'Michael Ross',
    techStack: ['Java', 'Spring Boot', 'Oracle', 'Angular'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-03-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/general-ledger',
    tags: ['sox-compliant', 'financial', 'audit-required'],
  },
  {
    id: makeId('APP', 6),
    name: APPLICATIONS.PAYROLL_SYSTEM,
    shortCode: 'PYRL',
    description: 'Employee payroll processing and tax management system.',
    domainId: MOCK_DOMAINS[0].id,
    domainName: DOMAINS.CORPORATE_FUNCTIONS,
    portfolioId: MOCK_PORTFOLIOS[0].id,
    portfolioName: PORTFOLIOS.FINANCE,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL,
    owner: MOCK_USERS[4].id,
    ownerName: 'Michael Ross',
    techStack: ['Java', 'Spring Boot', 'PostgreSQL'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-04-15T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/payroll-system',
    tags: ['pii', 'financial', 'scheduled-processing'],
  },
  {
    id: makeId('APP', 7),
    name: APPLICATIONS.TALENT_MANAGEMENT,
    shortCode: 'TLNT',
    description: 'Talent acquisition, onboarding, and performance management platform.',
    domainId: MOCK_DOMAINS[0].id,
    domainName: DOMAINS.CORPORATE_FUNCTIONS,
    portfolioId: MOCK_PORTFOLIOS[1].id,
    portfolioName: PORTFOLIOS.HR,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL,
    owner: MOCK_USERS[4].id,
    ownerName: 'Michael Ross',
    techStack: ['React', 'Node.js', 'MongoDB'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-08-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/talent-management',
    tags: ['pii', 'hr-system'],
  },
  {
    id: makeId('APP', 8),
    name: APPLICATIONS.MOBILE_IOS,
    shortCode: 'MIOS',
    description: 'Native iOS mobile application for members.',
    domainId: MOCK_DOMAINS[2].id,
    domainName: DOMAINS.DIGITAL_EXPERIENCE,
    portfolioId: MOCK_PORTFOLIOS[5].id,
    portfolioName: PORTFOLIOS.MOBILE_APPS,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[1].id,
    ownerName: 'Sarah Chen',
    techStack: ['Swift', 'SwiftUI', 'CoreData'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-09-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/mobile-ios',
    tags: ['mobile', 'customer-facing', 'app-store'],
  },
  {
    id: makeId('APP', 9),
    name: APPLICATIONS.MOBILE_ANDROID,
    shortCode: 'MAND',
    description: 'Native Android mobile application for members.',
    domainId: MOCK_DOMAINS[2].id,
    domainName: DOMAINS.DIGITAL_EXPERIENCE,
    portfolioId: MOCK_PORTFOLIOS[5].id,
    portfolioName: PORTFOLIOS.MOBILE_APPS,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[1].id,
    ownerName: 'Sarah Chen',
    techStack: ['Kotlin', 'Jetpack Compose', 'Room'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-09-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/mobile-android',
    tags: ['mobile', 'customer-facing', 'play-store'],
  },
  {
    id: makeId('APP', 10),
    name: APPLICATIONS.DATA_LAKE,
    shortCode: 'DLKE',
    description: 'Centralized data lake for enterprise data ingestion, storage, and processing.',
    domainId: MOCK_DOMAINS[3].id,
    domainName: DOMAINS.DATA_AND_ANALYTICS,
    portfolioId: MOCK_PORTFOLIOS[6].id,
    portfolioName: PORTFOLIOS.DATA_PLATFORM,
    criticalityTier: CRITICALITY_TIERS.MISSION_CRITICAL,
    owner: MOCK_USERS[5].id,
    ownerName: 'Lisa Nguyen',
    techStack: ['Python', 'Spark', 'Databricks', 'Delta Lake'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.DEV],
    onboardedAt: '2023-05-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/data-lake',
    tags: ['big-data', 'etl', 'data-governance'],
  },
  {
    id: makeId('APP', 11),
    name: APPLICATIONS.BI_REPORTS,
    shortCode: 'BIRP',
    description: 'Business intelligence reporting and dashboard platform.',
    domainId: MOCK_DOMAINS[3].id,
    domainName: DOMAINS.DATA_AND_ANALYTICS,
    portfolioId: MOCK_PORTFOLIOS[7].id,
    portfolioName: PORTFOLIOS.ANALYTICS_ENGINE,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL,
    owner: MOCK_USERS[5].id,
    ownerName: 'Lisa Nguyen',
    techStack: ['Python', 'Snowflake', 'Tableau', 'dbt'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-07-15T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/bi-reports',
    tags: ['analytics', 'reporting', 'executive-dashboards'],
  },
  {
    id: makeId('APP', 12),
    name: APPLICATIONS.SSO_GATEWAY,
    shortCode: 'SSOG',
    description: 'Single sign-on gateway for enterprise identity and access management.',
    domainId: MOCK_DOMAINS[4].id,
    domainName: DOMAINS.SECURITY_AND_COMPLIANCE,
    portfolioId: MOCK_PORTFOLIOS[8].id,
    portfolioName: PORTFOLIOS.IDENTITY_ACCESS,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[3].id,
    ownerName: 'Priya Patel',
    techStack: ['Java', 'Spring Security', 'Redis', 'LDAP'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-02-15T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/sso-gateway',
    tags: ['security', 'authentication', 'zero-trust'],
  },
  {
    id: makeId('APP', 13),
    name: APPLICATIONS.SIEM_PLATFORM,
    shortCode: 'SIEM',
    description: 'Security information and event management platform for threat detection.',
    domainId: MOCK_DOMAINS[4].id,
    domainName: DOMAINS.SECURITY_AND_COMPLIANCE,
    portfolioId: MOCK_PORTFOLIOS[9].id,
    portfolioName: PORTFOLIOS.THREAT_MANAGEMENT,
    criticalityTier: CRITICALITY_TIERS.MISSION_CRITICAL,
    owner: MOCK_USERS[3].id,
    ownerName: 'Priya Patel',
    techStack: ['Python', 'Elasticsearch', 'Kafka', 'Kibana'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.DEV],
    onboardedAt: '2023-03-10T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/siem-platform',
    tags: ['security', 'threat-detection', 'compliance'],
  },
  {
    id: makeId('APP', 14),
    name: APPLICATIONS.VM_MANAGER,
    shortCode: 'VMMG',
    description: 'Virtual machine lifecycle management and provisioning system.',
    domainId: MOCK_DOMAINS[5].id,
    domainName: DOMAINS.INFRASTRUCTURE_SERVICES,
    portfolioId: MOCK_PORTFOLIOS[11].id,
    portfolioName: PORTFOLIOS.ON_PREM_INFRA,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL,
    owner: MOCK_USERS[6].id,
    ownerName: 'David Kumar',
    techStack: ['Python', 'Ansible', 'Terraform', 'VMware'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.DEV],
    onboardedAt: '2023-06-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/vm-manager',
    tags: ['infrastructure', 'automation', 'provisioning'],
  },
  {
    id: makeId('APP', 15),
    name: APPLICATIONS.SAP_CORE,
    shortCode: 'SAPC',
    description: 'SAP ERP core modules for finance, procurement, and supply chain.',
    domainId: MOCK_DOMAINS[6].id,
    domainName: DOMAINS.ENTERPRISE_PLATFORMS,
    portfolioId: MOCK_PORTFOLIOS[12].id,
    portfolioName: PORTFOLIOS.ERP,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_CRITICAL,
    owner: MOCK_USERS[7].id,
    ownerName: 'Emma Johnson',
    techStack: ['ABAP', 'SAP HANA', 'Fiori'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.PRE_PROD, ENVIRONMENTS.QA, ENVIRONMENTS.DEV],
    onboardedAt: '2023-02-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/sap-core',
    tags: ['erp', 'sox-compliant', 'enterprise'],
  },
  {
    id: makeId('APP', 16),
    name: APPLICATIONS.SALESFORCE_CRM,
    shortCode: 'SFCR',
    description: 'Salesforce CRM for sales pipeline, customer engagement, and service management.',
    domainId: MOCK_DOMAINS[6].id,
    domainName: DOMAINS.ENTERPRISE_PLATFORMS,
    portfolioId: MOCK_PORTFOLIOS[13].id,
    portfolioName: PORTFOLIOS.CRM,
    criticalityTier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL,
    owner: MOCK_USERS[7].id,
    ownerName: 'Emma Johnson',
    techStack: ['Apex', 'Lightning', 'Salesforce Platform'],
    environments: [ENVIRONMENTS.PROD, ENVIRONMENTS.UAT, ENVIRONMENTS.DEV],
    onboardedAt: '2023-04-01T10:00:00Z',
    status: 'active',
    repoUrl: 'https://github.com/horizon-org/salesforce-crm',
    tags: ['crm', 'sales', 'customer-engagement'],
  },
]);

// ---------------------------------------------------------------------------
// Mock Pipeline Configurations
// ---------------------------------------------------------------------------
export const MOCK_PIPELINE_CONFIGS = Object.freeze([
  {
    id: makeId('PIP', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    name: 'member-portal-ci-cd',
    description: 'Full CI/CD pipeline for Member Portal with security scanning.',
    sourceControl: TOOLS.GITHUB,
    cicdTool: TOOLS.JENKINS,
    artifactRepo: TOOLS.ARTIFACTORY,
    containerPlatform: TOOLS.KUBERNETES,
    securityTools: [TOOLS.SONARQUBE, TOOLS.CHECKMARX, TOOLS.SNYK, TOOLS.TWISTLOCK],
    monitoringTool: TOOLS.DYNATRACE,
    loggingTool: TOOLS.SPLUNK,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.ARTIFACT_PUBLISH,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.CONTAINER_SCAN,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.DAST,
      PIPELINE_STAGES.PERFORMANCE_TEST,
      PIPELINE_STAGES.DEPLOY_UAT,
      PIPELINE_STAGES.UAT_SIGN_OFF,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.SMOKE_TEST,
      PIPELINE_STAGES.DEPLOY_PROD,
      PIPELINE_STAGES.POST_DEPLOY_VALIDATION,
    ],
    triggers: ['push to main', 'pull request', 'scheduled nightly'],
    createdAt: '2023-06-20T10:00:00Z',
    updatedAt: '2024-10-15T14:30:00Z',
  },
  {
    id: makeId('PIP', 2),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    name: 'care-radius-ci-cd',
    description: 'Enterprise CI/CD pipeline for Care Radius with HIPAA compliance checks.',
    sourceControl: TOOLS.BITBUCKET,
    cicdTool: TOOLS.JENKINS,
    artifactRepo: TOOLS.NEXUS,
    containerPlatform: TOOLS.OPENSHIFT,
    securityTools: [TOOLS.FORTIFY, TOOLS.BLACK_DUCK, TOOLS.TWISTLOCK],
    monitoringTool: TOOLS.DYNATRACE,
    loggingTool: TOOLS.SPLUNK,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.ARTIFACT_PUBLISH,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.CONTAINER_SCAN,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.DAST,
      PIPELINE_STAGES.DEPLOY_UAT,
      PIPELINE_STAGES.UAT_SIGN_OFF,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.SMOKE_TEST,
      PIPELINE_STAGES.DEPLOY_PROD,
      PIPELINE_STAGES.POST_DEPLOY_VALIDATION,
    ],
    triggers: ['push to main', 'pull request'],
    createdAt: '2023-05-25T10:00:00Z',
    updatedAt: '2024-09-20T11:00:00Z',
  },
  {
    id: makeId('PIP', 3),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    name: 'api-gateway-ci-cd',
    description: 'Lightweight CI/CD pipeline for API Gateway microservice.',
    sourceControl: TOOLS.GITHUB,
    cicdTool: TOOLS.GITHUB_ACTIONS,
    artifactRepo: TOOLS.ARTIFACTORY,
    containerPlatform: TOOLS.KUBERNETES,
    securityTools: [TOOLS.SONARQUBE, TOOLS.SNYK, TOOLS.TWISTLOCK],
    monitoringTool: TOOLS.PROMETHEUS,
    loggingTool: TOOLS.ELASTIC,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.CONTAINER_SCAN,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.SMOKE_TEST,
      PIPELINE_STAGES.DEPLOY_PROD,
      PIPELINE_STAGES.POST_DEPLOY_VALIDATION,
    ],
    triggers: ['push to main', 'tag creation'],
    createdAt: '2023-04-15T10:00:00Z',
    updatedAt: '2024-11-01T09:00:00Z',
  },
  {
    id: makeId('PIP', 4),
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    name: 'nms-ci-cd',
    description: 'CI/CD pipeline for Network Monitoring System with performance testing.',
    sourceControl: TOOLS.GITLAB,
    cicdTool: TOOLS.GITLAB_CI,
    artifactRepo: TOOLS.NEXUS,
    containerPlatform: TOOLS.DOCKER,
    securityTools: [TOOLS.SONARQUBE, TOOLS.SNYK],
    monitoringTool: TOOLS.GRAFANA,
    loggingTool: TOOLS.ELASTIC,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.ARTIFACT_PUBLISH,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.PERFORMANCE_TEST,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.DEPLOY_PROD,
    ],
    triggers: ['push to main', 'merge request'],
    createdAt: '2023-07-05T10:00:00Z',
    updatedAt: '2024-10-28T16:00:00Z',
  },
  {
    id: makeId('PIP', 5),
    applicationId: MOCK_APPLICATIONS[4].id,
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    name: 'general-ledger-ci-cd',
    description: 'SOX-compliant CI/CD pipeline for General Ledger with full audit trail.',
    sourceControl: TOOLS.BITBUCKET,
    cicdTool: TOOLS.JENKINS,
    artifactRepo: TOOLS.ARTIFACTORY,
    containerPlatform: TOOLS.OPENSHIFT,
    securityTools: [TOOLS.FORTIFY, TOOLS.CHECKMARX, TOOLS.BLACK_DUCK, TOOLS.TWISTLOCK],
    monitoringTool: TOOLS.DYNATRACE,
    loggingTool: TOOLS.SPLUNK,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.ARTIFACT_PUBLISH,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.CONTAINER_SCAN,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.DAST,
      PIPELINE_STAGES.PERFORMANCE_TEST,
      PIPELINE_STAGES.DEPLOY_UAT,
      PIPELINE_STAGES.UAT_SIGN_OFF,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.SMOKE_TEST,
      PIPELINE_STAGES.DEPLOY_PROD,
      PIPELINE_STAGES.POST_DEPLOY_VALIDATION,
    ],
    triggers: ['push to main', 'pull request', 'manual approval'],
    createdAt: '2023-03-05T10:00:00Z',
    updatedAt: '2024-11-05T10:00:00Z',
  },
  {
    id: makeId('PIP', 6),
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    name: 'sso-gateway-ci-cd',
    description: 'Security-hardened CI/CD pipeline for SSO Gateway.',
    sourceControl: TOOLS.GITHUB,
    cicdTool: TOOLS.JENKINS,
    artifactRepo: TOOLS.ARTIFACTORY,
    containerPlatform: TOOLS.KUBERNETES,
    securityTools: [TOOLS.FORTIFY, TOOLS.CHECKMARX, TOOLS.SNYK, TOOLS.TWISTLOCK],
    monitoringTool: TOOLS.DYNATRACE,
    loggingTool: TOOLS.SPLUNK,
    stages: [
      PIPELINE_STAGES.SOURCE,
      PIPELINE_STAGES.BUILD,
      PIPELINE_STAGES.UNIT_TEST,
      PIPELINE_STAGES.SAST,
      PIPELINE_STAGES.SCA,
      PIPELINE_STAGES.ARTIFACT_PUBLISH,
      PIPELINE_STAGES.CONTAINER_BUILD,
      PIPELINE_STAGES.CONTAINER_SCAN,
      PIPELINE_STAGES.DEPLOY_DEV,
      PIPELINE_STAGES.INTEGRATION_TEST,
      PIPELINE_STAGES.DEPLOY_QA,
      PIPELINE_STAGES.DAST,
      PIPELINE_STAGES.DEPLOY_UAT,
      PIPELINE_STAGES.UAT_SIGN_OFF,
      PIPELINE_STAGES.DEPLOY_PRE_PROD,
      PIPELINE_STAGES.SMOKE_TEST,
      PIPELINE_STAGES.DEPLOY_PROD,
      PIPELINE_STAGES.POST_DEPLOY_VALIDATION,
    ],
    triggers: ['push to main', 'pull request', 'manual approval'],
    createdAt: '2023-02-20T10:00:00Z',
    updatedAt: '2024-10-30T12:00:00Z',
  },
]);

// ---------------------------------------------------------------------------
// Mock Pipeline Runs (Recent Executions)
// ---------------------------------------------------------------------------
export const MOCK_PIPELINE_RUNS = Object.freeze([
  {
    id: makeId('RUN', 1),
    pipelineId: MOCK_PIPELINE_CONFIGS[0].id,
    pipelineName: 'member-portal-ci-cd',
    applicationName: 'Member Portal',
    buildNumber: 342,
    status: PIPELINE_STATUSES.SUCCESS,
    triggeredBy: MOCK_USERS[1].username,
    trigger: 'push to main',
    branch: 'main',
    commitSha: 'a1b2c3d4e5f6',
    startedAt: '2024-11-10T08:15:00Z',
    completedAt: '2024-11-10T08:42:00Z',
    durationSeconds: 1620,
    stages: [
      { name: PIPELINE_STAGES.SOURCE, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 12 },
      { name: PIPELINE_STAGES.BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 145 },
      { name: PIPELINE_STAGES.UNIT_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 98 },
      { name: PIPELINE_STAGES.SAST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 210 },
      { name: PIPELINE_STAGES.SCA, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 65 },
      { name: PIPELINE_STAGES.ARTIFACT_PUBLISH, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 30 },
      { name: PIPELINE_STAGES.CONTAINER_BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 180 },
      { name: PIPELINE_STAGES.CONTAINER_SCAN, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 120 },
      { name: PIPELINE_STAGES.DEPLOY_DEV, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 90 },
      { name: PIPELINE_STAGES.INTEGRATION_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 240 },
      { name: PIPELINE_STAGES.DEPLOY_QA, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 90 },
      { name: PIPELINE_STAGES.DAST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 180 },
      { name: PIPELINE_STAGES.DEPLOY_PROD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 160 },
    ],
  },
  {
    id: makeId('RUN', 2),
    pipelineId: MOCK_PIPELINE_CONFIGS[1].id,
    pipelineName: 'care-radius-ci-cd',
    applicationName: 'Care Radius',
    buildNumber: 218,
    status: PIPELINE_STATUSES.FAILED,
    triggeredBy: MOCK_USERS[2].username,
    trigger: 'push to main',
    branch: 'main',
    commitSha: 'f6e5d4c3b2a1',
    startedAt: '2024-11-10T07:30:00Z',
    completedAt: '2024-11-10T07:48:00Z',
    durationSeconds: 1080,
    stages: [
      { name: PIPELINE_STAGES.SOURCE, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 10 },
      { name: PIPELINE_STAGES.BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 200 },
      { name: PIPELINE_STAGES.UNIT_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 150 },
      { name: PIPELINE_STAGES.SAST, status: PIPELINE_STATUSES.FAILED, durationSeconds: 320, errorMessage: '3 critical vulnerabilities detected in authentication module' },
      { name: PIPELINE_STAGES.SCA, status: PIPELINE_STATUSES.SKIPPED, durationSeconds: 0 },
      { name: PIPELINE_STAGES.ARTIFACT_PUBLISH, status: PIPELINE_STATUSES.SKIPPED, durationSeconds: 0 },
    ],
  },
  {
    id: makeId('RUN', 3),
    pipelineId: MOCK_PIPELINE_CONFIGS[2].id,
    pipelineName: 'api-gateway-ci-cd',
    applicationName: 'API Gateway',
    buildNumber: 567,
    status: PIPELINE_STATUSES.SUCCESS,
    triggeredBy: MOCK_USERS[6].username,
    trigger: 'tag creation',
    branch: 'main',
    commitSha: '1a2b3c4d5e6f',
    startedAt: '2024-11-10T06:00:00Z',
    completedAt: '2024-11-10T06:18:00Z',
    durationSeconds: 1080,
    stages: [
      { name: PIPELINE_STAGES.SOURCE, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 8 },
      { name: PIPELINE_STAGES.BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 95 },
      { name: PIPELINE_STAGES.UNIT_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 72 },
      { name: PIPELINE_STAGES.SAST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 140 },
      { name: PIPELINE_STAGES.SCA, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 45 },
      { name: PIPELINE_STAGES.CONTAINER_BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 120 },
      { name: PIPELINE_STAGES.CONTAINER_SCAN, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 90 },
      { name: PIPELINE_STAGES.DEPLOY_DEV, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 60 },
      { name: PIPELINE_STAGES.INTEGRATION_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 180 },
      { name: PIPELINE_STAGES.DEPLOY_PROD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 120 },
    ],
  },
  {
    id: makeId('RUN', 4),
    pipelineId: MOCK_PIPELINE_CONFIGS[3].id,
    pipelineName: 'nms-ci-cd',
    applicationName: 'Network Monitoring System',
    buildNumber: 189,
    status: PIPELINE_STATUSES.RUNNING,
    triggeredBy: MOCK_USERS[2].username,
    trigger: 'push to main',
    branch: 'feature/alerting-v2',
    commitSha: '9f8e7d6c5b4a',
    startedAt: '2024-11-10T09:00:00Z',
    completedAt: null,
    durationSeconds: null,
    stages: [
      { name: PIPELINE_STAGES.SOURCE, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 9 },
      { name: PIPELINE_STAGES.BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 110 },
      { name: PIPELINE_STAGES.UNIT_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 85 },
      { name: PIPELINE_STAGES.SAST, status: PIPELINE_STATUSES.RUNNING, durationSeconds: null },
      { name: PIPELINE_STAGES.SCA, status: PIPELINE_STATUSES.PENDING, durationSeconds: null },
    ],
  },
  {
    id: makeId('RUN', 5),
    pipelineId: MOCK_PIPELINE_CONFIGS[4].id,
    pipelineName: 'general-ledger-ci-cd',
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    buildNumber: 412,
    status: PIPELINE_STATUSES.SUCCESS,
    triggeredBy: MOCK_USERS[4].username,
    trigger: 'manual approval',
    branch: 'release/2024.11',
    commitSha: '3c4d5e6f7a8b',
    startedAt: '2024-11-09T22:00:00Z',
    completedAt: '2024-11-09T22:55:00Z',
    durationSeconds: 3300,
    stages: [
      { name: PIPELINE_STAGES.SOURCE, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 11 },
      { name: PIPELINE_STAGES.BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 250 },
      { name: PIPELINE_STAGES.UNIT_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 180 },
      { name: PIPELINE_STAGES.SAST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 350 },
      { name: PIPELINE_STAGES.SCA, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 90 },
      { name: PIPELINE_STAGES.ARTIFACT_PUBLISH, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 40 },
      { name: PIPELINE_STAGES.CONTAINER_BUILD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 200 },
      { name: PIPELINE_STAGES.CONTAINER_SCAN, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 150 },
      { name: PIPELINE_STAGES.DEPLOY_DEV, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 100 },
      { name: PIPELINE_STAGES.INTEGRATION_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 300 },
      { name: PIPELINE_STAGES.DEPLOY_QA, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 100 },
      { name: PIPELINE_STAGES.DAST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 280 },
      { name: PIPELINE_STAGES.PERFORMANCE_TEST, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 420 },
      { name: PIPELINE_STAGES.DEPLOY_UAT, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 100 },
      { name: PIPELINE_STAGES.DEPLOY_PROD, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 180 },
      { name: PIPELINE_STAGES.POST_DEPLOY_VALIDATION, status: PIPELINE_STATUSES.SUCCESS, durationSeconds: 120 },
    ],
  },
]);

// ---------------------------------------------------------------------------
// Mock MELT (Metrics, Events, Logs, Traces) Data
// ---------------------------------------------------------------------------
export const MOCK_MELT_METRICS = Object.freeze([
  {
    id: makeId('MLT', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    environment: ENVIRONMENTS.PROD,
    timestamp: '2024-11-10T09:00:00Z',
    metrics: {
      cpuUtilization: 42.5,
      memoryUtilization: 68.3,
      requestsPerSecond: 1250,
      responseTimeP50Ms: 85,
      responseTimeP95Ms: 245,
      responseTimeP99Ms: 520,
      errorRate: 0.12,
      activeConnections: 3420,
      throughputMbps: 156.8,
      availability: 99.98,
    },
  },
  {
    id: makeId('MLT', 2),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    environment: ENVIRONMENTS.PROD,
    timestamp: '2024-11-10T09:00:00Z',
    metrics: {
      cpuUtilization: 55.2,
      memoryUtilization: 72.1,
      requestsPerSecond: 890,
      responseTimeP50Ms: 120,
      responseTimeP95Ms: 380,
      responseTimeP99Ms: 750,
      errorRate: 0.25,
      activeConnections: 2180,
      throughputMbps: 98.4,
      availability: 99.95,
    },
  },
  {
    id: makeId('MLT', 3),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    environment: ENVIRONMENTS.PROD,
    timestamp: '2024-11-10T09:00:00Z',
    metrics: {
      cpuUtilization: 35.8,
      memoryUtilization: 45.6,
      requestsPerSecond: 8500,
      responseTimeP50Ms: 12,
      responseTimeP95Ms: 45,
      responseTimeP99Ms: 120,
      errorRate: 0.05,
      activeConnections: 15200,
      throughputMbps: 420.5,
      availability: 99.999,
    },
  },
  {
    id: makeId('MLT', 4),
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    environment: ENVIRONMENTS.PROD,
    timestamp: '2024-11-10T09:00:00Z',
    metrics: {
      cpuUtilization: 62.1,
      memoryUtilization: 78.4,
      requestsPerSecond: 450,
      responseTimeP50Ms: 200,
      responseTimeP95Ms: 650,
      responseTimeP99Ms: 1200,
      errorRate: 0.08,
      activeConnections: 890,
      throughputMbps: 75.2,
      availability: 99.97,
    },
  },
  {
    id: makeId('MLT', 5),
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    environment: ENVIRONMENTS.PROD,
    timestamp: '2024-11-10T09:00:00Z',
    metrics: {
      cpuUtilization: 28.4,
      memoryUtilization: 52.7,
      requestsPerSecond: 5200,
      responseTimeP50Ms: 18,
      responseTimeP95Ms: 55,
      responseTimeP99Ms: 150,
      errorRate: 0.02,
      activeConnections: 9800,
      throughputMbps: 210.3,
      availability: 99.999,
    },
  },
]);

// ---------------------------------------------------------------------------
// Mock MELT Events
// ---------------------------------------------------------------------------
export const MOCK_MELT_EVENTS = Object.freeze([
  {
    id: makeId('EVT', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    environment: ENVIRONMENTS.PROD,
    type: 'deployment',
    severity: SEVERITY_LEVELS.INFO,
    title: 'Deployment v2.14.3 completed successfully',
    description: 'Member Portal version 2.14.3 deployed to production with zero downtime.',
    timestamp: '2024-11-10T08:42:00Z',
    source: TOOLS.JENKINS,
    metadata: { version: '2.14.3', buildNumber: 342, deploymentStrategy: 'blue-green' },
  },
  {
    id: makeId('EVT', 2),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    environment: ENVIRONMENTS.PROD,
    type: 'alert',
    severity: SEVERITY_LEVELS.HIGH,
    title: 'Response time degradation detected',
    description: 'P95 response time exceeded 500ms threshold for Care Radius API endpoints.',
    timestamp: '2024-11-10T07:15:00Z',
    source: TOOLS.DYNATRACE,
    metadata: { metric: 'response_time_p95', threshold: 500, actual: 680, unit: 'ms' },
  },
  {
    id: makeId('EVT', 3),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    environment: ENVIRONMENTS.PROD,
    type: 'scaling',
    severity: SEVERITY_LEVELS.INFO,
    title: 'Auto-scaling triggered: 4 → 6 pods',
    description: 'Horizontal pod autoscaler increased replica count due to CPU utilization above 70%.',
    timestamp: '2024-11-10T06:30:00Z',
    source: TOOLS.KUBERNETES,
    metadata: { previousReplicas: 4, newReplicas: 6, cpuUtilization: 73.5 },
  },
  {
    id: makeId('EVT', 4),
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    environment: ENVIRONMENTS.PROD,
    type: 'alert',
    severity: SEVERITY_LEVELS.CRITICAL,
    title: 'Network device unreachable: core-switch-01',
    description: 'Core switch in datacenter DC-East is not responding to SNMP polls for 5 minutes.',
    timestamp: '2024-11-10T05:45:00Z',
    source: 'NMS',
    metadata: { deviceId: 'core-switch-01', datacenter: 'DC-East', lastSeen: '2024-11-10T05:40:00Z' },
  },
  {
    id: makeId('EVT', 5),
    applicationId: MOCK_APPLICATIONS[4].id,
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    environment: ENVIRONMENTS.PROD,
    type: 'security',
    severity: SEVERITY_LEVELS.MEDIUM,
    title: 'Failed login attempts threshold exceeded',
    description: '15 failed login attempts detected from IP 10.45.23.100 within 5 minutes.',
    timestamp: '2024-11-10T04:20:00Z',
    source: TOOLS.SPLUNK,
    metadata: { sourceIp: '10.45.23.100', attempts: 15, timeWindowMinutes: 5 },
  },
]);

// ---------------------------------------------------------------------------
// Mock MELT Logs
// ---------------------------------------------------------------------------
export const MOCK_MELT_LOGS = Object.freeze([
  {
    id: makeId('LOG', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    environment: ENVIRONMENTS.PROD,
    level: 'ERROR',
    message: 'Failed to process payment: timeout connecting to payment gateway',
    timestamp: '2024-11-10T09:12:34Z',
    source: 'payment-service',
    traceId: 'trace-abc123def456',
    spanId: 'span-789ghi',
    metadata: { userId: 'USR-45678', transactionId: 'TXN-99012', gateway: 'stripe' },
  },
  {
    id: makeId('LOG', 2),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    environment: ENVIRONMENTS.PROD,
    level: 'WARN',
    message: 'Cache miss rate above threshold: 35% (threshold: 20%)',
    timestamp: '2024-11-10T09:10:00Z',
    source: 'cache-manager',
    traceId: null,
    spanId: null,
    metadata: { cacheType: 'redis', missRate: 35, threshold: 20 },
  },
  {
    id: makeId('LOG', 3),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    environment: ENVIRONMENTS.PROD,
    level: 'ERROR',
    message: 'Database connection pool exhausted: max connections (100) reached',
    timestamp: '2024-11-10T07:14:22Z',
    source: 'db-connection-pool',
    traceId: 'trace-xyz789abc012',
    spanId: 'span-345def',
    metadata: { poolSize: 100, activeConnections: 100, waitingRequests: 23 },
  },
  {
    id: makeId('LOG', 4),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    environment: ENVIRONMENTS.PROD,
    level: 'INFO',
    message: 'Rate limit applied: client app-mobile-ios exceeded 1000 req/min',
    timestamp: '2024-11-10T08:55:00Z',
    source: 'rate-limiter',
    traceId: null,
    spanId: null,
    metadata: { clientId: 'app-mobile-ios', limit: 1000, window: '1m', action: 'throttle' },
  },
  {
    id: makeId('LOG', 5),
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    environment: ENVIRONMENTS.PROD,
    level: 'WARN',
    message: 'Token refresh failed for user: expired refresh token',
    timestamp: '2024-11-10T09:05:12Z',
    source: 'auth-service',
    traceId: 'trace-mno345pqr678',
    spanId: 'span-901stu',
    metadata: { userId: 'USR-12345', tokenAge: '8h', maxAge: '7h' },
  },
]);

// ---------------------------------------------------------------------------
// Mock MELT Traces
// ---------------------------------------------------------------------------
export const MOCK_MELT_TRACES = Object.freeze([
  {
    id: makeId('TRC', 1),
    traceId: 'trace-abc123def456',
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    environment: ENVIRONMENTS.PROD,
    operationName: 'POST /api/payments/process',
    startTime: '2024-11-10T09:12:30Z',
    durationMs: 4520,
    status: 'error',
    spans: [
      { spanId: 'span-001', operationName: 'payment-service.processPayment', durationMs: 4520, status: 'error' },
      { spanId: 'span-002', operationName: 'validation-service.validateCard', durationMs: 120, status: 'ok' },
      { spanId: 'span-003', operationName: 'fraud-service.checkFraud', durationMs: 350, status: 'ok' },
      { spanId: 'span-004', operationName: 'gateway-client.chargeCard', durationMs: 3800, status: 'error' },
    ],
  },
  {
    id: makeId('TRC', 2),
    traceId: 'trace-xyz789abc012',
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    environment: ENVIRONMENTS.PROD,
    operationName: 'GET /api/providers/search',
    startTime: '2024-11-10T07:14:20Z',
    durationMs: 2800,
    status: 'error',
    spans: [
      { spanId: 'span-010', operationName: 'provider-service.search', durationMs: 2800, status: 'error' },
      { spanId: 'span-011', operationName: 'db.query.providers', durationMs: 2500, status: 'error' },
      { spanId: 'span-012', operationName: 'cache.get.providerList', durationMs: 5, status: 'ok' },
    ],
  },
  {
    id: makeId('TRC', 3),
    traceId: 'trace-ghi456jkl789',
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    environment: ENVIRONMENTS.PROD,
    operationName: 'GET /api/v1/members/profile',
    startTime: '2024-11-10T08:50:00Z',
    durationMs: 42,
    status: 'ok',
    spans: [
      { spanId: 'span-020', operationName: 'gateway.route', durationMs: 42, status: 'ok' },
      { spanId: 'span-021', operationName: 'auth.validateToken', durationMs: 8, status: 'ok' },
      { spanId: 'span-022', operationName: 'rateLimit.check', durationMs: 2, status: 'ok' },
      { spanId: 'span-023', operationName: 'upstream.memberService', durationMs: 28, status: 'ok' },
    ],
  },
]);

// ---------------------------------------------------------------------------
// Mock KPI Metrics
// ---------------------------------------------------------------------------
export const MOCK_KPI_METRICS = Object.freeze([
  {
    id: makeId('KPI', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 18,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 2.4,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 4.2,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 0.45,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 94.5,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 27,
      [KPI_METRICS.CODE_COVERAGE]: 82.3,
      [KPI_METRICS.VULNERABILITY_COUNT]: 12,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 0,
      [KPI_METRICS.OPEN_INCIDENTS]: 3,
      [KPI_METRICS.MTTR_INCIDENTS]: 1.2,
      [KPI_METRICS.SLA_COMPLIANCE]: 99.5,
      [KPI_METRICS.AVAILABILITY]: 99.98,
      [KPI_METRICS.ERROR_RATE]: 0.12,
      [KPI_METRICS.RESPONSE_TIME_P95]: 245,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 96.8,
      [KPI_METRICS.COMPLIANCE_SCORE]: 92,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 48,
      [KPI_METRICS.TOIL_REDUCTION]: 35,
      [KPI_METRICS.ONBOARDING_TIME]: 3,
    },
  },
  {
    id: makeId('KPI', 2),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 8,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 5.2,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 8.5,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 1.8,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 87.2,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 42,
      [KPI_METRICS.CODE_COVERAGE]: 75.6,
      [KPI_METRICS.VULNERABILITY_COUNT]: 28,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 3,
      [KPI_METRICS.OPEN_INCIDENTS]: 7,
      [KPI_METRICS.MTTR_INCIDENTS]: 3.5,
      [KPI_METRICS.SLA_COMPLIANCE]: 97.8,
      [KPI_METRICS.AVAILABILITY]: 99.95,
      [KPI_METRICS.ERROR_RATE]: 0.25,
      [KPI_METRICS.RESPONSE_TIME_P95]: 380,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 88.4,
      [KPI_METRICS.COMPLIANCE_SCORE]: 85,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 120,
      [KPI_METRICS.TOIL_REDUCTION]: 18,
      [KPI_METRICS.ONBOARDING_TIME]: 7,
    },
  },
  {
    id: makeId('KPI', 3),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 32,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 0.8,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 1.5,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 0.15,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 98.2,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 18,
      [KPI_METRICS.CODE_COVERAGE]: 91.2,
      [KPI_METRICS.VULNERABILITY_COUNT]: 2,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 0,
      [KPI_METRICS.OPEN_INCIDENTS]: 1,
      [KPI_METRICS.MTTR_INCIDENTS]: 0.3,
      [KPI_METRICS.SLA_COMPLIANCE]: 99.99,
      [KPI_METRICS.AVAILABILITY]: 99.999,
      [KPI_METRICS.ERROR_RATE]: 0.05,
      [KPI_METRICS.RESPONSE_TIME_P95]: 45,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 99.1,
      [KPI_METRICS.COMPLIANCE_SCORE]: 97,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 12,
      [KPI_METRICS.TOIL_REDUCTION]: 62,
      [KPI_METRICS.ONBOARDING_TIME]: 1,
    },
  },
  {
    id: makeId('KPI', 4),
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 12,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 3.1,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 5.8,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 0.9,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 91.5,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 22,
      [KPI_METRICS.CODE_COVERAGE]: 78.9,
      [KPI_METRICS.VULNERABILITY_COUNT]: 8,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 1,
      [KPI_METRICS.OPEN_INCIDENTS]: 4,
      [KPI_METRICS.MTTR_INCIDENTS]: 1.5,
      [KPI_METRICS.SLA_COMPLIANCE]: 98.9,
      [KPI_METRICS.AVAILABILITY]: 99.97,
      [KPI_METRICS.ERROR_RATE]: 0.08,
      [KPI_METRICS.RESPONSE_TIME_P95]: 650,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 93.5,
      [KPI_METRICS.COMPLIANCE_SCORE]: 89,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 65,
      [KPI_METRICS.TOIL_REDUCTION]: 28,
      [KPI_METRICS.ONBOARDING_TIME]: 4,
    },
  },
  {
    id: makeId('KPI', 5),
    applicationId: MOCK_APPLICATIONS[4].id,
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 4,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 8.5,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 2.1,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 2.5,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 96.8,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 55,
      [KPI_METRICS.CODE_COVERAGE]: 88.1,
      [KPI_METRICS.VULNERABILITY_COUNT]: 5,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 0,
      [KPI_METRICS.OPEN_INCIDENTS]: 2,
      [KPI_METRICS.MTTR_INCIDENTS]: 2.0,
      [KPI_METRICS.SLA_COMPLIANCE]: 99.8,
      [KPI_METRICS.AVAILABILITY]: 99.99,
      [KPI_METRICS.ERROR_RATE]: 0.03,
      [KPI_METRICS.RESPONSE_TIME_P95]: 320,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 98.5,
      [KPI_METRICS.COMPLIANCE_SCORE]: 96,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 35,
      [KPI_METRICS.TOIL_REDUCTION]: 42,
      [KPI_METRICS.ONBOARDING_TIME]: 5,
    },
  },
  {
    id: makeId('KPI', 6),
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    period: '2024-11',
    metrics: {
      [KPI_METRICS.DEPLOYMENT_FREQUENCY]: 10,
      [KPI_METRICS.LEAD_TIME_FOR_CHANGES]: 1.5,
      [KPI_METRICS.CHANGE_FAILURE_RATE]: 2.0,
      [KPI_METRICS.MEAN_TIME_TO_RECOVERY]: 0.25,
      [KPI_METRICS.PIPELINE_SUCCESS_RATE]: 97.5,
      [KPI_METRICS.PIPELINE_DURATION_AVG]: 32,
      [KPI_METRICS.CODE_COVERAGE]: 89.5,
      [KPI_METRICS.VULNERABILITY_COUNT]: 3,
      [KPI_METRICS.CRITICAL_VULNERABILITY_COUNT]: 0,
      [KPI_METRICS.OPEN_INCIDENTS]: 1,
      [KPI_METRICS.MTTR_INCIDENTS]: 0.5,
      [KPI_METRICS.SLA_COMPLIANCE]: 99.95,
      [KPI_METRICS.AVAILABILITY]: 99.999,
      [KPI_METRICS.ERROR_RATE]: 0.02,
      [KPI_METRICS.RESPONSE_TIME_P95]: 55,
      [KPI_METRICS.SECURITY_SCAN_PASS_RATE]: 99.5,
      [KPI_METRICS.COMPLIANCE_SCORE]: 98,
      [KPI_METRICS.TECHNICAL_DEBT_HOURS]: 18,
      [KPI_METRICS.TOIL_REDUCTION]: 55,
      [KPI_METRICS.ONBOARDING_TIME]: 2,
    },
  },
]);

// ---------------------------------------------------------------------------
// Mock KPI Historical Trends (for charts)
// ---------------------------------------------------------------------------
export const MOCK_KPI_TRENDS = Object.freeze([
  {
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    metric: KPI_METRICS.DEPLOYMENT_FREQUENCY,
    unit: 'deployments/month',
    dataPoints: [
      { period: '2024-06', value: 10 },
      { period: '2024-07', value: 12 },
      { period: '2024-08', value: 14 },
      { period: '2024-09', value: 15 },
      { period: '2024-10', value: 16 },
      { period: '2024-11', value: 18 },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    metric: KPI_METRICS.LEAD_TIME_FOR_CHANGES,
    unit: 'days',
    dataPoints: [
      { period: '2024-06', value: 4.5 },
      { period: '2024-07', value: 4.0 },
      { period: '2024-08', value: 3.5 },
      { period: '2024-09', value: 3.0 },
      { period: '2024-10', value: 2.8 },
      { period: '2024-11', value: 2.4 },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    metric: KPI_METRICS.CHANGE_FAILURE_RATE,
    unit: '%',
    dataPoints: [
      { period: '2024-06', value: 8.5 },
      { period: '2024-07', value: 7.2 },
      { period: '2024-08', value: 6.1 },
      { period: '2024-09', value: 5.5 },
      { period: '2024-10', value: 4.8 },
      { period: '2024-11', value: 4.2 },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    metric: KPI_METRICS.MEAN_TIME_TO_RECOVERY,
    unit: 'hours',
    dataPoints: [
      { period: '2024-06', value: 1.8 },
      { period: '2024-07', value: 1.5 },
      { period: '2024-08', value: 1.2 },
      { period: '2024-09', value: 0.9 },
      { period: '2024-10', value: 0.6 },
      { period: '2024-11', value: 0.45 },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    metric: KPI_METRICS.DEPLOYMENT_FREQUENCY,
    unit: 'deployments/month',
    dataPoints: [
      { period: '2024-06', value: 20 },
      { period: '2024-07', value: 22 },
      { period: '2024-08', value: 25 },
      { period: '2024-09', value: 28 },
      { period: '2024-10', value: 30 },
      { period: '2024-11', value: 32 },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    metric: KPI_METRICS.AVAILABILITY,
    unit: '%',
    dataPoints: [
      { period: '2024-06', value: 99.99 },
      { period: '2024-07', value: 99.995 },
      { period: '2024-08', value: 99.998 },
      { period: '2024-09', value: 99.999 },
      { period: '2024-10', value: 99.999 },
      { period: '2024-11', value: 99.999 },
    ],
  },
]);

// ---------------------------------------------------------------------------
// Mock Compliance Artifacts
// ---------------------------------------------------------------------------
export const MOCK_COMPLIANCE_ARTIFACTS = Object.freeze([
  {
    id: makeId('CMP', 1),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    type: COMPLIANCE_ARTIFACT_TYPES.SAST_REPORT,
    name: 'SAST Scan Report - Member Portal v2.14.3',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-11-10T08:25:00Z',
    generatedBy: 'Jenkins Pipeline',
    tool: TOOLS.CHECKMARX,
    findings: { critical: 0, high: 0, medium: 3, low: 12, info: 28 },
    fileUrl: '/artifacts/sast/member-portal-v2.14.3.pdf',
    expiresAt: '2025-05-10T08:25:00Z',
  },
  {
    id: makeId('CMP', 2),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    type: COMPLIANCE_ARTIFACT_TYPES.SCA_REPORT,
    name: 'SCA Scan Report - Member Portal v2.14.3',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-11-10T08:28:00Z',
    generatedBy: 'Jenkins Pipeline',
    tool: TOOLS.SNYK,
    findings: { critical: 0, high: 1, medium: 5, low: 18, info: 0 },
    fileUrl: '/artifacts/sca/member-portal-v2.14.3.pdf',
    expiresAt: '2025-05-10T08:28:00Z',
  },
  {
    id: makeId('CMP', 3),
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    type: COMPLIANCE_ARTIFACT_TYPES.CONTAINER_SCAN_REPORT,
    name: 'Container Scan Report - Member Portal v2.14.3',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-11-10T08:32:00Z',
    generatedBy: 'Jenkins Pipeline',
    tool: TOOLS.TWISTLOCK,
    findings: { critical: 0, high: 0, medium: 2, low: 8, info: 15 },
    fileUrl: '/artifacts/container-scan/member-portal-v2.14.3.pdf',
    expiresAt: '2025-05-10T08:32:00Z',
  },
  {
    id: makeId('CMP', 4),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    type: COMPLIANCE_ARTIFACT_TYPES.SAST_REPORT,
    name: 'SAST Scan Report - Care Radius v3.8.1',
    status: COMPLIANCE_STATUSES.NON_COMPLIANT,
    generatedAt: '2024-11-10T07:45:00Z',
    generatedBy: 'Jenkins Pipeline',
    tool: TOOLS.FORTIFY,
    findings: { critical: 3, high: 5, medium: 12, low: 25, info: 40 },
    fileUrl: '/artifacts/sast/care-radius-v3.8.1.pdf',
    expiresAt: '2025-05-10T07:45:00Z',
  },
  {
    id: makeId('CMP', 5),
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    type: COMPLIANCE_ARTIFACT_TYPES.PENETRATION_TEST,
    name: 'Annual Penetration Test - Care Radius 2024',
    status: COMPLIANCE_STATUSES.PARTIAL,
    generatedAt: '2024-10-15T10:00:00Z',
    generatedBy: 'Security Team',
    tool: 'External Vendor',
    findings: { critical: 1, high: 3, medium: 8, low: 15, info: 22 },
    fileUrl: '/artifacts/pentest/care-radius-2024.pdf',
    expiresAt: '2025-10-15T10:00:00Z',
  },
  {
    id: makeId('CMP', 6),
    applicationId: MOCK_APPLICATIONS[4].id,
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    type: COMPLIANCE_ARTIFACT_TYPES.COMPLIANCE_CHECKLIST,
    name: 'SOX Compliance Checklist - General Ledger Q4 2024',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-10-01T10:00:00Z',
    generatedBy: 'Priya Patel',
    tool: 'Manual Review',
    findings: { critical: 0, high: 0, medium: 0, low: 2, info: 5 },
    fileUrl: '/artifacts/compliance/general-ledger-sox-q4-2024.pdf',
    expiresAt: '2025-01-01T10:00:00Z',
  },
  {
    id: makeId('CMP', 7),
    applicationId: MOCK_APPLICATIONS[4].id,
    applicationName: APPLICATIONS.GENERAL_LEDGER,
    type: COMPLIANCE_ARTIFACT_TYPES.CHANGE_REQUEST,
    name: 'CR-2024-1105 - General Ledger Release 2024.11',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-11-05T10:00:00Z',
    generatedBy: 'Michael Ross',
    tool: TOOLS.SERVICENOW,
    findings: null,
    fileUrl: '/artifacts/change-requests/CR-2024-1105.pdf',
    expiresAt: null,
  },
  {
    id: makeId('CMP', 8),
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    type: COMPLIANCE_ARTIFACT_TYPES.DAST_REPORT,
    name: 'DAST Scan Report - API Gateway v5.2.0',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-11-08T14:00:00Z',
    generatedBy: 'GitHub Actions Pipeline',
    tool: 'OWASP ZAP',
    findings: { critical: 0, high: 0, medium: 1, low: 4, info: 10 },
    fileUrl: '/artifacts/dast/api-gateway-v5.2.0.pdf',
    expiresAt: '2025-05-08T14:00:00Z',
  },
  {
    id: makeId('CMP', 9),
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    type: COMPLIANCE_ARTIFACT_TYPES.RISK_ASSESSMENT,
    name: 'Risk Assessment - SSO Gateway 2024',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-09-15T10:00:00Z',
    generatedBy: 'Priya Patel',
    tool: 'Manual Review',
    findings: { critical: 0, high: 1, medium: 3, low: 5, info: 8 },
    fileUrl: '/artifacts/risk/sso-gateway-2024.pdf',
    expiresAt: '2025-09-15T10:00:00Z',
  },
  {
    id: makeId('CMP', 10),
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    type: COMPLIANCE_ARTIFACT_TYPES.DISASTER_RECOVERY_PLAN,
    name: 'DR Plan - Network Monitoring System 2024',
    status: COMPLIANCE_STATUSES.PENDING_REVIEW,
    generatedAt: '2024-10-20T10:00:00Z',
    generatedBy: 'James Wilson',
    tool: 'Confluence',
    findings: null,
    fileUrl: '/artifacts/dr/nms-dr-plan-2024.pdf',
    expiresAt: '2025-10-20T10:00:00Z',
  },
  {
    id: makeId('CMP', 11),
    applicationId: MOCK_APPLICATIONS[12].id,
    applicationName: APPLICATIONS.SIEM_PLATFORM,
    type: COMPLIANCE_ARTIFACT_TYPES.EVIDENCE_PACKAGE,
    name: 'Evidence Package - SIEM Platform SOC2 2024',
    status: COMPLIANCE_STATUSES.COMPLIANT,
    generatedAt: '2024-10-30T10:00:00Z',
    generatedBy: 'Priya Patel',
    tool: 'Manual Collection',
    findings: null,
    fileUrl: '/artifacts/evidence/siem-soc2-2024.pdf',
    expiresAt: '2025-10-30T10:00:00Z',
  },
]);

// ---------------------------------------------------------------------------
// Mock Audit Logs
// ---------------------------------------------------------------------------
export const MOCK_AUDIT_LOGS = Object.freeze([
  {
    id: makeId('AUD', 1),
    timestamp: '2024-11-10T09:00:00Z',
    userId: MOCK_USERS[0].id,
    username: MOCK_USERS[0].username,
    action: 'USER_LOGIN',
    resource: 'auth',
    resourceId: null,
    description: 'User admin.horizon logged in successfully.',
    ipAddress: '10.20.30.40',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    metadata: { method: 'SSO', sessionId: 'sess-abc123' },
  },
  {
    id: makeId('AUD', 2),
    timestamp: '2024-11-10T08:42:00Z',
    userId: MOCK_USERS[1].id,
    username: MOCK_USERS[1].username,
    action: 'PIPELINE_DEPLOY',
    resource: 'pipeline',
    resourceId: MOCK_PIPELINE_CONFIGS[0].id,
    description: 'Pipeline member-portal-ci-cd build #342 deployed to production.',
    ipAddress: '10.20.30.41',
    userAgent: 'Jenkins/2.426',
    status: 'success',
    metadata: { buildNumber: 342, environment: ENVIRONMENTS.PROD, version: '2.14.3' },
  },
  {
    id: makeId('AUD', 3),
    timestamp: '2024-11-10T07:48:00Z',
    userId: MOCK_USERS[2].id,
    username: MOCK_USERS[2].username,
    action: 'PIPELINE_FAILED',
    resource: 'pipeline',
    resourceId: MOCK_PIPELINE_CONFIGS[1].id,
    description: 'Pipeline care-radius-ci-cd build #218 failed at SAST stage.',
    ipAddress: '10.20.30.42',
    userAgent: 'Jenkins/2.426',
    status: 'failure',
    metadata: { buildNumber: 218, failedStage: PIPELINE_STAGES.SAST, reason: 'Critical vulnerabilities detected' },
  },
  {
    id: makeId('AUD', 4),
    timestamp: '2024-11-10T07:30:00Z',
    userId: MOCK_USERS[0].id,
    username: MOCK_USERS[0].username,
    action: 'APPLICATION_ONBOARD',
    resource: 'application',
    resourceId: MOCK_APPLICATIONS[0].id,
    description: 'Application Member Portal configuration updated.',
    ipAddress: '10.20.30.40',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    metadata: { field: 'tags', oldValue: ['customer-facing', 'high-traffic'], newValue: ['customer-facing', 'high-traffic', 'pci-compliant'] },
  },
  {
    id: makeId('AUD', 5),
    timestamp: '2024-11-09T22:55:00Z',
    userId: MOCK_USERS[4].id,
    username: MOCK_USERS[4].username,
    action: 'PIPELINE_DEPLOY',
    resource: 'pipeline',
    resourceId: MOCK_PIPELINE_CONFIGS[4].id,
    description: 'Pipeline general-ledger-ci-cd build #412 deployed to production.',
    ipAddress: '10.20.30.45',
    userAgent: 'Jenkins/2.426',
    status: 'success',
    metadata: { buildNumber: 412, environment: ENVIRONMENTS.PROD, version: '2024.11.0' },
  },
  {
    id: makeId('AUD', 6),
    timestamp: '2024-11-09T18:00:00Z',
    userId: MOCK_USERS[3].id,
    username: MOCK_USERS[3].username,
    action: 'COMPLIANCE_REVIEW',
    resource: 'compliance',
    resourceId: MOCK_COMPLIANCE_ARTIFACTS[3].id,
    description: 'Compliance artifact reviewed: SAST Scan Report - Care Radius v3.8.1 marked as Non-Compliant.',
    ipAddress: '10.20.30.44',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    metadata: { artifactType: COMPLIANCE_ARTIFACT_TYPES.SAST_REPORT, previousStatus: COMPLIANCE_STATUSES.PENDING_REVIEW, newStatus: COMPLIANCE_STATUSES.NON_COMPLIANT },
  },
  {
    id: makeId('AUD', 7),
    timestamp: '2024-11-09T16:30:00Z',
    userId: MOCK_USERS[0].id,
    username: MOCK_USERS[0].username,
    action: 'USER_ROLE_CHANGE',
    resource: 'user',
    resourceId: MOCK_USERS[5].id,
    description: 'User lisa.nguyen role updated from Engineer to Owner.',
    ipAddress: '10.20.30.40',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    metadata: { previousRole: ROLES.ENGINEER, newRole: ROLES.OWNER },
  },
  {
    id: makeId('AUD', 8),
    timestamp: '2024-11-09T14:00:00Z',
    userId: MOCK_USERS[6].id,
    username: MOCK_USERS[6].username,
    action: 'TOOLCHAIN_CONFIG_UPDATE',
    resource: 'toolchain',
    resourceId: 'kubernetes',
    description: 'Kubernetes cluster configuration updated for API Gateway.',
    ipAddress: '10.20.30.47',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    metadata: { applicationId: MOCK_APPLICATIONS[2].id, field: 'replicaCount', oldValue: 2, newValue: 4 },
  },
  {
    id: makeId('AUD', 9),
    timestamp: '2024-11-09T11:00:00Z',
    userId: MOCK_USERS[1].id,
    username: MOCK_USERS[1].username,
    action: 'REPORT_EXPORT',
    resource: 'report',
    resourceId: null,
    description: 'DORA metrics report exported for Member Portal (2024-Q4).',
    ipAddress: '10.20.30.41',
    userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
    status: 'success',
    metadata: { reportType: 'DORA', format: 'PDF', period: '2024-Q4', applicationName: 'Member Portal' },
  },
  {
    id: makeId('AUD', 10),
    timestamp: '2024-11-09T09:15:00Z',
    userId: MOCK_USERS[7].id,
    username: MOCK_USERS[7].username,
    action: 'INCIDENT_CREATE',
    resource: 'incident',
    resourceId: 'INC-2024-1109',
    description: 'Incident INC-2024-1109 created: SAP Core batch job failure.',
    ipAddress: '10.20.30.48',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    metadata: { severity: SEVERITY_LEVELS.HIGH, applicationName: APPLICATIONS.SAP_CORE, assignmentGroup: 'Enterprise Platforms' },
  },
  {
    id: makeId('AUD', 11),
    timestamp: '2024-11-08T20:00:00Z',
    userId: null,
    username: 'system',
    action: 'SCHEDULED_SCAN',
    resource: 'security',
    resourceId: null,
    description: 'Scheduled nightly security scan completed for all onboarded applications.',
    ipAddress: '10.20.30.1',
    userAgent: 'CronJob/v1',
    status: 'success',
    metadata: { applicationsScanned: 16, totalFindings: 142, criticalFindings: 4 },
  },
  {
    id: makeId('AUD', 12),
    timestamp: '2024-11-08T15:30:00Z',
    userId: MOCK_USERS[3].id,
    username: MOCK_USERS[3].username,
    action: 'COMPLIANCE_ARTIFACT_UPLOAD',
    resource: 'compliance',
    resourceId: MOCK_COMPLIANCE_ARTIFACTS[8].id,
    description: 'Risk Assessment uploaded for SSO Gateway.',
    ipAddress: '10.20.30.44',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    status: 'success',
    metadata: { artifactType: COMPLIANCE_ARTIFACT_TYPES.RISK_ASSESSMENT, applicationName: APPLICATIONS.SSO_GATEWAY },
  },
]);

// ---------------------------------------------------------------------------
// Mock Incidents
// ---------------------------------------------------------------------------
export const MOCK_INCIDENTS = Object.freeze([
  {
    id: 'INC-2024-1110-001',
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    title: 'Payment processing timeout errors',
    description: 'Intermittent timeout errors when processing payments through the payment gateway.',
    severity: SEVERITY_LEVELS.HIGH,
    status: 'Open',
    assignee: MOCK_USERS[1].username,
    assignmentGroup: 'Digital Experience',
    createdAt: '2024-11-10T09:12:00Z',
    updatedAt: '2024-11-10T09:30:00Z',
    resolvedAt: null,
    environment: ENVIRONMENTS.PROD,
    source: TOOLS.DYNATRACE,
    relatedChangeId: null,
    rootCause: null,
    impact: 'Approximately 2% of payment transactions failing.',
  },
  {
    id: 'INC-2024-1110-002',
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    title: 'Database connection pool exhaustion',
    description: 'Care Radius experiencing database connection pool exhaustion during peak hours.',
    severity: SEVERITY_LEVELS.CRITICAL,
    status: 'In Progress',
    assignee: MOCK_USERS[2].username,
    assignmentGroup: 'Health and Network',
    createdAt: '2024-11-10T07:14:00Z',
    updatedAt: '2024-11-10T08:00:00Z',
    resolvedAt: null,
    environment: ENVIRONMENTS.PROD,
    source: TOOLS.SPLUNK,
    relatedChangeId: null,
    rootCause: 'Connection leak in provider search module',
    impact: 'Provider search functionality degraded for all users.',
  },
  {
    id: 'INC-2024-1110-003',
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    title: 'Core switch unreachable in DC-East',
    description: 'Core switch core-switch-01 in datacenter DC-East not responding to monitoring polls.',
    severity: SEVERITY_LEVELS.CRITICAL,
    status: 'Open',
    assignee: MOCK_USERS[6].username,
    assignmentGroup: 'Infrastructure Services',
    createdAt: '2024-11-10T05:45:00Z',
    updatedAt: '2024-11-10T06:00:00Z',
    resolvedAt: null,
    environment: ENVIRONMENTS.PROD,
    source: 'NMS',
    relatedChangeId: null,
    rootCause: null,
    impact: 'Potential network connectivity issues for DC-East hosted services.',
  },
  {
    id: 'INC-2024-1109-001',
    applicationId: MOCK_APPLICATIONS[14].id,
    applicationName: APPLICATIONS.SAP_CORE,
    title: 'SAP batch job failure - month-end close',
    description: 'Month-end financial close batch job failed during GL posting step.',
    severity: SEVERITY_LEVELS.HIGH,
    status: 'Resolved',
    assignee: MOCK_USERS[7].username,
    assignmentGroup: 'Enterprise Platforms',
    createdAt: '2024-11-09T09:15:00Z',
    updatedAt: '2024-11-09T12:30:00Z',
    resolvedAt: '2024-11-09T12:30:00Z',
    environment: ENVIRONMENTS.PROD,
    source: TOOLS.SERVICENOW,
    relatedChangeId: 'CR-2024-1105',
    rootCause: 'Memory allocation exceeded for large posting batch',
    impact: 'Month-end close delayed by 3 hours.',
  },
  {
    id: 'INC-2024-1108-001',
    applicationId: MOCK_APPLICATIONS[11].id,
    applicationName: APPLICATIONS.SSO_GATEWAY,
    title: 'Elevated token refresh failures',
    description: 'Increased rate of token refresh failures observed across multiple client applications.',
    severity: SEVERITY_LEVELS.MEDIUM,
    status: 'Resolved',
    assignee: MOCK_USERS[3].username,
    assignmentGroup: 'Security and Compliance',
    createdAt: '2024-11-08T14:00:00Z',
    updatedAt: '2024-11-08T16:45:00Z',
    resolvedAt: '2024-11-08T16:45:00Z',
    environment: ENVIRONMENTS.PROD,
    source: TOOLS.DYNATRACE,
    relatedChangeId: null,
    rootCause: 'Clock skew between SSO nodes causing premature token expiration',
    impact: 'Users experiencing intermittent re-authentication prompts.',
  },
]);

// ---------------------------------------------------------------------------
// Mock Notifications
// ---------------------------------------------------------------------------
export const MOCK_NOTIFICATIONS = Object.freeze([
  {
    id: makeId('NTF', 1),
    type: 'pipeline_failure',
    title: 'Pipeline Failed: care-radius-ci-cd #218',
    message: 'SAST stage failed with 3 critical vulnerabilities detected.',
    severity: SEVERITY_LEVELS.HIGH,
    applicationName: 'Care Radius',
    timestamp: '2024-11-10T07:48:00Z',
    read: false,
    actionUrl: '/pipelines/PIP-0002/runs/RUN-0002',
  },
  {
    id: makeId('NTF', 2),
    type: 'incident_created',
    title: 'Critical Incident: Core switch unreachable',
    message: 'Core switch core-switch-01 in DC-East is not responding.',
    severity: SEVERITY_LEVELS.CRITICAL,
    applicationName: 'Network Monitoring System',
    timestamp: '2024-11-10T05:45:00Z',
    read: false,
    actionUrl: '/incidents/INC-2024-1110-003',
  },
  {
    id: makeId('NTF', 3),
    type: 'deployment_success',
    title: 'Deployment Successful: Member Portal v2.14.3',
    message: 'Member Portal v2.14.3 deployed to production successfully.',
    severity: SEVERITY_LEVELS.INFO,
    applicationName: 'Member Portal',
    timestamp: '2024-11-10T08:42:00Z',
    read: true,
    actionUrl: '/pipelines/PIP-0001/runs/RUN-0001',
  },
  {
    id: makeId('NTF', 4),
    type: 'compliance_alert',
    title: 'Non-Compliant: Care Radius SAST Report',
    message: 'SAST scan report for Care Radius v3.8.1 marked as non-compliant.',
    severity: SEVERITY_LEVELS.HIGH,
    applicationName: 'Care Radius',
    timestamp: '2024-11-09T18:00:00Z',
    read: false,
    actionUrl: '/compliance/CMP-0004',
  },
  {
    id: makeId('NTF', 5),
    type: 'security_scan',
    title: 'Nightly Security Scan Complete',
    message: '16 applications scanned. 4 critical findings require attention.',
    severity: SEVERITY_LEVELS.MEDIUM,
    applicationName: null,
    timestamp: '2024-11-08T20:00:00Z',
    read: true,
    actionUrl: '/compliance',
  },
]);

// ---------------------------------------------------------------------------
// Mock Dashboard Summary
// ---------------------------------------------------------------------------
export const MOCK_DASHBOARD_SUMMARY = Object.freeze({
  totalApplications: MOCK_APPLICATIONS.length,
  totalDomains: MOCK_DOMAINS.length,
  totalPortfolios: MOCK_PORTFOLIOS.length,
  totalPipelines: MOCK_PIPELINE_CONFIGS.length,
  activeIncidents: MOCK_INCIDENTS.filter((i) => i.status !== 'Resolved').length,
  criticalIncidents: MOCK_INCIDENTS.filter((i) => i.severity === SEVERITY_LEVELS.CRITICAL && i.status !== 'Resolved').length,
  pipelineSuccessRate: 92.4,
  averageLeadTime: 3.6,
  averageDeploymentFrequency: 14.0,
  averageChangeFailureRate: 4.4,
  averageMttr: 0.95,
  complianceScore: 91.2,
  securityScanPassRate: 95.8,
  overallAvailability: 99.98,
  applicationsByDomain: [
    { domain: DOMAINS.CORPORATE_FUNCTIONS, count: 3 },
    { domain: DOMAINS.HEALTH_AND_NETWORK, count: 2 },
    { domain: DOMAINS.DIGITAL_EXPERIENCE, count: 3 },
    { domain: DOMAINS.DATA_AND_ANALYTICS, count: 2 },
    { domain: DOMAINS.SECURITY_AND_COMPLIANCE, count: 2 },
    { domain: DOMAINS.INFRASTRUCTURE_SERVICES, count: 2 },
    { domain: DOMAINS.ENTERPRISE_PLATFORMS, count: 2 },
  ],
  applicationsByCriticality: [
    { tier: CRITICALITY_TIERS.BUSINESS_CRITICAL, count: 7 },
    { tier: CRITICALITY_TIERS.MISSION_CRITICAL, count: 4 },
    { tier: CRITICALITY_TIERS.BUSINESS_OPERATIONAL, count: 4 },
    { tier: CRITICALITY_TIERS.ADMIN_SERVICES, count: 1 },
  ],
  recentDeployments: [
    { applicationName: 'Member Portal', version: '2.14.3', environment: ENVIRONMENTS.PROD, status: PIPELINE_STATUSES.SUCCESS, timestamp: '2024-11-10T08:42:00Z' },
    { applicationName: APPLICATIONS.GENERAL_LEDGER, version: '2024.11.0', environment: ENVIRONMENTS.PROD, status: PIPELINE_STATUSES.SUCCESS, timestamp: '2024-11-09T22:55:00Z' },
    { applicationName: 'API Gateway', version: '5.2.0', environment: ENVIRONMENTS.PROD, status: PIPELINE_STATUSES.SUCCESS, timestamp: '2024-11-10T06:18:00Z' },
    { applicationName: 'Care Radius', version: '3.8.1', environment: ENVIRONMENTS.DEV, status: PIPELINE_STATUSES.FAILED, timestamp: '2024-11-10T07:48:00Z' },
  ],
});

// ---------------------------------------------------------------------------
// Mock Toolchain Assignments (per application)
// ---------------------------------------------------------------------------
export const MOCK_TOOLCHAIN_ASSIGNMENTS = Object.freeze([
  {
    applicationId: MOCK_APPLICATIONS[0].id,
    applicationName: 'Member Portal',
    tools: [
      { category: TOOLCHAIN_CATEGORIES.SOURCE_CONTROL, tool: TOOLS.GITHUB, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CI_CD, tool: TOOLS.JENKINS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ARTIFACT_MANAGEMENT, tool: TOOLS.ARTIFACTORY, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CONTAINERIZATION, tool: TOOLS.KUBERNETES, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SONARQUBE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.CHECKMARX, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SNYK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.TWISTLOCK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.DYNATRACE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.LOGGING, tool: TOOLS.SPLUNK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ITSM, tool: TOOLS.SERVICENOW, configured: true },
      { category: TOOLCHAIN_CATEGORIES.COLLABORATION, tool: TOOLS.JIRA, configured: true },
      { category: TOOLCHAIN_CATEGORIES.COLLABORATION, tool: TOOLS.CONFLUENCE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.TESTING, tool: TOOLS.CYPRESS, configured: true },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[1].id,
    applicationName: 'Care Radius',
    tools: [
      { category: TOOLCHAIN_CATEGORIES.SOURCE_CONTROL, tool: TOOLS.BITBUCKET, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CI_CD, tool: TOOLS.JENKINS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ARTIFACT_MANAGEMENT, tool: TOOLS.NEXUS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CONTAINERIZATION, tool: TOOLS.OPENSHIFT, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.FORTIFY, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.BLACK_DUCK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.TWISTLOCK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.DYNATRACE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.LOGGING, tool: TOOLS.SPLUNK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ITSM, tool: TOOLS.SERVICENOW, configured: true },
      { category: TOOLCHAIN_CATEGORIES.COLLABORATION, tool: TOOLS.JIRA, configured: true },
      { category: TOOLCHAIN_CATEGORIES.TESTING, tool: TOOLS.SELENIUM, configured: true },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[2].id,
    applicationName: 'API Gateway',
    tools: [
      { category: TOOLCHAIN_CATEGORIES.SOURCE_CONTROL, tool: TOOLS.GITHUB, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CI_CD, tool: TOOLS.GITHUB_ACTIONS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ARTIFACT_MANAGEMENT, tool: TOOLS.ARTIFACTORY, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CONTAINERIZATION, tool: TOOLS.KUBERNETES, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SONARQUBE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SNYK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.TWISTLOCK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.PROMETHEUS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.GRAFANA, configured: true },
      { category: TOOLCHAIN_CATEGORIES.LOGGING, tool: TOOLS.ELASTIC, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ITSM, tool: TOOLS.SERVICENOW, configured: true },
      { category: TOOLCHAIN_CATEGORIES.COLLABORATION, tool: TOOLS.SLACK, configured: true },
    ],
  },
  {
    applicationId: MOCK_APPLICATIONS[3].id,
    applicationName: 'Network Monitoring System',
    tools: [
      { category: TOOLCHAIN_CATEGORIES.SOURCE_CONTROL, tool: TOOLS.GITLAB, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CI_CD, tool: TOOLS.GITLAB_CI, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ARTIFACT_MANAGEMENT, tool: TOOLS.NEXUS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.CONTAINERIZATION, tool: TOOLS.DOCKER, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SONARQUBE, configured: true },
      { category: TOOLCHAIN_CATEGORIES.SECURITY_SCANNING, tool: TOOLS.SNYK, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.GRAFANA, configured: true },
      { category: TOOLCHAIN_CATEGORIES.MONITORING, tool: TOOLS.PROMETHEUS, configured: true },
      { category: TOOLCHAIN_CATEGORIES.LOGGING, tool: TOOLS.ELASTIC, configured: true },
      { category: TOOLCHAIN_CATEGORIES.ITSM, tool: TOOLS.SERVICENOW, configured: true },
      { category: TOOLCHAIN_CATEGORIES.COLLABORATION, tool: TOOLS.TEAMS, configured: true },
    ],
  },
]);

// ---------------------------------------------------------------------------
// Lookup Helpers
// ---------------------------------------------------------------------------

/**
 * Get a mock application by its ID.
 * @param {string} id
 * @returns {Object|undefined}
 */
export const getApplicationById = (id) => {
  return MOCK_APPLICATIONS.find((app) => app.id === id);
};

/**
 * Get mock applications by domain name.
 * @param {string} domainName
 * @returns {Array<Object>}
 */
export const getApplicationsByDomain = (domainName) => {
  return MOCK_APPLICATIONS.filter((app) => app.domainName === domainName);
};

/**
 * Get mock applications by portfolio name.
 * @param {string} portfolioName
 * @returns {Array<Object>}
 */
export const getApplicationsByPortfolio = (portfolioName) => {
  return MOCK_APPLICATIONS.filter((app) => app.portfolioName === portfolioName);
};

/**
 * Get mock KPI metrics for a given application ID.
 * @param {string} applicationId
 * @returns {Object|undefined}
 */
export const getKpiByApplicationId = (applicationId) => {
  return MOCK_KPI_METRICS.find((kpi) => kpi.applicationId === applicationId);
};

/**
 * Get mock pipeline configs for a given application ID.
 * @param {string} applicationId
 * @returns {Array<Object>}
 */
export const getPipelinesByApplicationId = (applicationId) => {
  return MOCK_PIPELINE_CONFIGS.filter((p) => p.applicationId === applicationId);
};

/**
 * Get mock compliance artifacts for a given application ID.
 * @param {string} applicationId
 * @returns {Array<Object>}
 */
export const getComplianceByApplicationId = (applicationId) => {
  return MOCK_COMPLIANCE_ARTIFACTS.filter((a) => a.applicationId === applicationId);
};

/**
 * Get mock incidents for a given application ID.
 * @param {string} applicationId
 * @returns {Array<Object>}
 */
export const getIncidentsByApplicationId = (applicationId) => {
  return MOCK_INCIDENTS.filter((i) => i.applicationId === applicationId);
};

/**
 * Get mock MELT metrics for a given application ID.
 * @param {string} applicationId
 * @returns {Object|undefined}
 */
export const getMeltByApplicationId = (applicationId) => {
  return MOCK_MELT_METRICS.find((m) => m.applicationId === applicationId);
};

/**
 * Get a mock user by their ID.
 * @param {string} id
 * @returns {Object|undefined}
 */
export const getUserById = (id) => {
  return MOCK_USERS.find((u) => u.id === id);
};

/**
 * Get mock toolchain assignments for a given application ID.
 * @param {string} applicationId
 * @returns {Object|undefined}
 */
export const getToolchainByApplicationId = (applicationId) => {
  return MOCK_TOOLCHAIN_ASSIGNMENTS.find((t) => t.applicationId === applicationId);
};